/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package redpoll.grupos;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import redpoll.auth.InterfazLogin;

/**
 *
 * @author Usuario
 */
public class NuevoFormularioGrupo extends javax.swing.JFrame {
  private VentanaFormularioGrupos VentanaFormularioGrupos;
  private DefaultTableModel modelo = new DefaultTableModel();
  private Grupo grup;
  
  // Metodo constructor
  public NuevoFormularioGrupo() {
    this.setUndecorated(true);
    initComponents();
    String[] nombreColumnas = new String[] { "Id", "Tipo", "Descripción" };
    this.modelo.setColumnIdentifiers(nombreColumnas);
    this.tbGrupo.setModel(modelo);
    this.actualizarTabla();
  }

  private void abrirFormularioGrupo(Grupo grup) {

    this.VentanaFormularioGrupos = new VentanaFormularioGrupos(this, true, grup);
    VentanaFormularioGrupos.setVisible(true);
    // Revisar
    if (VentanaFormularioGrupos.confirmacion()) {
      Grupo nuevoGrupo = VentanaFormularioGrupos.consultarGrupo();
      if (grup == null) {
        // Revisar
        if (GestorGrupo.getInstance().validarExistencia(String.valueOf(nuevoGrupo.getIdGrupo()))) {
          JOptionPane.showMessageDialog(this, "Grupo ya existente", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
          GestorGrupo.getInstance().agregarGrupo(nuevoGrupo);
          this.actualizarTabla();
        }
      } else {
        GestorGrupo.getInstance().editarGrupo(nuevoGrupo);
      }
    }
  }
  //valida la seleccion de la fila
  private boolean validarSeleccion() {
    boolean valor = false;
    int filaSeleccionada = this.tbGrupo.getSelectedRow();
    if (filaSeleccionada != -1) {
      valor = true;
    } else {
      JOptionPane.showMessageDialog(this, "Primero selccione un grupo.");
    }
    return valor;
  }

  private void actualizarTabla() {

    this.modelo.setRowCount(0);
    for (Grupo grupo : GestorGrupo.getInstance().getGrupos().values()) {
      this.modelo.addRow(new Object[] { grupo.getIdGrupo(), grupo.getTipo(), grupo.getDescripcion() });
    }

  }
  //
  private void update() {
    int filaSeleccionada = this.tbGrupo.getSelectedRow();
    if (this.validarSeleccion()) {
      String tipoGrupo = String.valueOf(this.tbGrupo.getValueAt(filaSeleccionada, 0));
      Grupo grupo = GestorGrupo.getInstance().obtenerGrupo(tipoGrupo);
      this.abrirFormularioGrupo(grupo);
      this.actualizarTabla();
      // Solucion
    }

  }

  // Eliminar
  private void eliminarGrupo() {
    int filaSeleccionada = this.tbGrupo.getSelectedRow();
    if (this.validarSeleccion()) {
      String idGrupo = String.valueOf(this.tbGrupo.getValueAt(filaSeleccionada, 0));
      GestorGrupo.getInstance().eliminarGrupo(idGrupo);
      this.actualizarTabla();
    }
  }

  private void formFiltro() {

    FiltroGrupos guiFiltro = new FiltroGrupos(this, true);
    guiFiltro.setVisible(true);

    if (guiFiltro.confirmacion()) {
      this.modelo.setRowCount(0);

      for (Grupo grupo : GestorGrupo.getInstance().getGrupos().values()) {
        boolean filtro = true;
        if (guiFiltro.getCheckNombre() && !String.valueOf(grupo.getTipo()).contentEquals(guiFiltro.getDatos(0))) {
          filtro = false;
        }
        if (guiFiltro.getCheckCedula()
            && !String.valueOf(grupo.getDescripcion()).contentEquals(guiFiltro.getDatos(1))) {
          filtro = false;
        }

        if (filtro) {
          this.modelo.addRow(new Object[] {
              grupo.getIdGrupo(),
              grupo.getTipo(),
              grupo.getDescripcion()
          });
        }

      }

      this.tbGrupo.setModel(modelo);
      this.tbGrupo.repaint();
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbGrupos = new javax.swing.JTable();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        lblGrupos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGrupo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        lblIngreseTipo = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblCrear = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblVolver = new javax.swing.JLabel();

        tbGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Grupo", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGrupos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tbGruposComponentAdded(evt);
            }
        });
        tbGrupos.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tbGruposCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tbGruposInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tbGrupos);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jInternalFrame1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 207, 178));

        lblGrupos.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/Grupos.png"))); // NOI18N
        lblGrupos.setText("Gestión de Grupos");

        tbGrupo.setBackground(new java.awt.Color(255, 255, 255));
        tbGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Tipo", "Descripcion"
            }
        ));
        jScrollPane2.setViewportView(tbGrupo);

        jPanel2.setBackground(new java.awt.Color(197, 186, 175));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/crear.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/editar.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/eliminar.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnFiltrar.setBackground(new java.awt.Color(255, 255, 255));
        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/buscar.png"))); // NOI18N
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        lblIngreseTipo.setText("Buscar");

        lblEliminar.setText("Eliminar");

        lblEditar.setText("Editar");

        lblCrear.setText("Crear");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCrear)
                        .addGap(28, 28, 28)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblEditar)
                        .addGap(59, 59, 59)
                        .addComponent(lblEliminar)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(lblIngreseTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFiltrar)
                    .addComponent(btnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEliminar)
                        .addComponent(lblEditar)
                        .addComponent(lblCrear))
                    .addComponent(lblIngreseTipo))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/volver.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblVolver.setText("Volver");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblVolver)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblGrupos))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGrupos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVolver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        InterfazLogin.menuPrincipal();
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

  private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarActionPerformed
    // TODO add your handling code here:
    this.abrirFormularioGrupo(grup);

  }// GEN-LAST:event_btnAgregarActionPerformed

  private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditarActionPerformed
    // TODO add your handling code here:
    this.update();
  }// GEN-LAST:event_btnEditarActionPerformed

  private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEliminarActionPerformed
    // TODO add your handling code here:

    this.eliminarGrupo();
  }// GEN-LAST:event_btnEliminarActionPerformed

  private void tbGruposComponentAdded(java.awt.event.ContainerEvent evt) {// GEN-FIRST:event_tbGruposComponentAdded
    // TODO add your handling code here:
  }// GEN-LAST:event_tbGruposComponentAdded

  private void tbGruposInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {// GEN-FIRST:event_tbGruposInputMethodTextChanged
    // TODO add your handling code here:
  }// GEN-LAST:event_tbGruposInputMethodTextChanged

  private void tbGruposCaretPositionChanged(java.awt.event.InputMethodEvent evt) {// GEN-FIRST:event_tbGruposCaretPositionChanged
    // TODO add your handling code here:
  }// GEN-LAST:event_tbGruposCaretPositionChanged

  private void jInternalFrame1FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jInternalFrame1FocusLost
    // TODO add your handling code here:
  }// GEN-LAST:event_jInternalFrame1FocusLost

  private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btbFiltrarActionPerformed
    this.formFiltro();
  }// GEN-LAST:event_btbFiltrarActionPerformed

  /**
   * @param args the command line arguments
   */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCrear;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblGrupos;
    private javax.swing.JLabel lblIngreseTipo;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JTable tbGrupo;
    private javax.swing.JTable tbGrupos;
    // End of variables declaration//GEN-END:variables
}
