/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package redpoll;

/**
 *
 * @author Extremetech SC
 */

public class GestorUsuarioRoles extends javax.swing.JFrame {

    /**
     * Creates new form GestorUsuarioRoles
     */
    //instancia
     private GestorUsuario manager;
     
    public GestorUsuarioRoles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensajeAgregar = new java.awt.Label();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        lblShowAgregar = new java.awt.Label();
        lblMostrarConsultar = new javax.swing.JLabel();
        lblMostrarEliminar = new javax.swing.JLabel();
        lblMostrarEditar = new javax.swing.JLabel();
        lblMostrarAgregar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        btxAgregar = new javax.swing.JButton();
        btxEliminar = new javax.swing.JButton();
        btxEditar = new javax.swing.JButton();
        btcConsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCRUDUsuarios = new javax.swing.JTable();

        lblMensajeAgregar.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblMensajeAgregar.setText("label1");

        label1.setText("label1");

        label2.setText("label2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );

        lblShowAgregar.setFont(new java.awt.Font("Goudy Old Style", 0, 48)); // NOI18N
        lblShowAgregar.setText("label3");

        lblMostrarConsultar.setText("Consultar");

        lblMostrarEliminar.setText("Eliminar");

        lblMostrarEditar.setText("Editar");

        lblMostrarAgregar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMostrarAgregar.setText("Agregar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        label3.setText("label3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        btxAgregar.setText("Agregar");
        btxAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxAgregarActionPerformed(evt);
            }
        });

        btxEliminar.setText("Eliminar");

        btxEditar.setText("Editar");

        btcConsultar.setText("Consultar");
        btcConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcConsultarActionPerformed(evt);
            }
        });

        jLabel1.setText("Administrador ");

        tbCRUDUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tbCRUDUsuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btxAgregar)
                                .addGap(47, 47, 47)
                                .addComponent(btxEliminar)
                                .addGap(57, 57, 57)
                                .addComponent(btxEditar)
                                .addGap(51, 51, 51)
                                .addComponent(btcConsultar)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btxAgregar)
                    .addComponent(btxEliminar)
                    .addComponent(btxEditar)
                    .addComponent(btcConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btxAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxAgregarActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_btxAgregarActionPerformed

    private void btcConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcConsultar;
    private javax.swing.JButton btxAgregar;
    private javax.swing.JButton btxEditar;
    private javax.swing.JButton btxEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label lblMensajeAgregar;
    private javax.swing.JLabel lblMostrarAgregar;
    private javax.swing.JLabel lblMostrarConsultar;
    private javax.swing.JLabel lblMostrarEditar;
    private javax.swing.JLabel lblMostrarEliminar;
    private java.awt.Label lblShowAgregar;
    private javax.swing.JTable tbCRUDUsuarios;
    // End of variables declaration//GEN-END:variables
}
