package redpoll.auth;

import redpoll.animales.JFAnimal;
import redpoll.chequeos.JFChequeo;
import redpoll.grupos.NuevoFormularioGrupo;
import redpoll.produccion.GuiProduccion;
import redpoll.propietarios.GuiPropietario;
import redpoll.reportes.MenuReportes;
import redpoll.roles.GestionRoles;
import redpoll.vacunas.JFVacuna;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kristel Gamboa M
 */
public class GUIMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenuPrincipal
     */
    public GUIMenuPrincipal() {
        this.setUndecorated(true);
        initComponents();
        if(!GestionRoles.getInstance().mostrarRole(GestionUsuarios.getTokenRoleActual()).getAnimales()){
            this.btnAnimales.setVisible(false);
            this.lblAnimales.setVisible(false);
        }
        if(!GestionRoles.getInstance().mostrarRole(GestionUsuarios.getTokenRoleActual()).getChequeos()){
            this.btnChequeos.setVisible(false);
            this.lblChequeos.setVisible(false);
        }
        if(!GestionRoles.getInstance().mostrarRole(GestionUsuarios.getTokenRoleActual()).getGrupos()){
            this.btnGrupos.setVisible(false);
            this.lblGrupos.setVisible(false);
        }
        if(!GestionRoles.getInstance().mostrarRole(GestionUsuarios.getTokenRoleActual()).getProduccion()){
            this.btnProduccion.setVisible(false);
            this.lblProduccion.setVisible(false);
        }
        if(!GestionRoles.getInstance().mostrarRole(GestionUsuarios.getTokenRoleActual()).getPropietarios()){
            this.btnPropietarios.setVisible(false);
            this.lblPropietarios.setVisible(false);
        }
        if(!GestionRoles.getInstance().mostrarRole(GestionUsuarios.getTokenRoleActual()).getVacunas()){
            this.btnVacunas.setVisible(false);
            this.lblVacunas.setVisible(false);
        }
        if(!GestionRoles.getInstance().mostrarRole(GestionUsuarios.getTokenRoleActual()).getUsuarios()){
            this.btnUsuarios.setVisible(false);
            this.lblUsuarios.setVisible(false);
        }
        if(!GestionRoles.getInstance().mostrarRole(GestionUsuarios.getTokenRoleActual()).getReportes()){
            this.btnReportes.setVisible(false);
            this.lblReportes.setVisible(false);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAnimales = new javax.swing.JButton();
        btnVacunas = new javax.swing.JButton();
        btnChequeos = new javax.swing.JButton();
        btnGrupos = new javax.swing.JButton();
        btnProduccion = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnPropietarios = new javax.swing.JButton();
        lblAnimales = new javax.swing.JLabel();
        lblProduccion = new javax.swing.JLabel();
        lblVacunas = new javax.swing.JLabel();
        lblChequeos = new javax.swing.JLabel();
        lblGrupos = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        lblPropietarios = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        lblTitulo2 = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 207, 178));

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/menuPrincipal.png"))); // NOI18N
        lblTitulo.setText("Menu Principal");

        jPanel2.setBackground(new java.awt.Color(197, 186, 175));

        btnAnimales.setBackground(new java.awt.Color(255, 255, 255));
        btnAnimales.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnAnimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/animalesMenuP.png"))); // NOI18N
        btnAnimales.setBorderPainted(false);
        btnAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalesActionPerformed(evt);
            }
        });

        btnVacunas.setBackground(new java.awt.Color(255, 255, 255));
        btnVacunas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnVacunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/vacunasMenuP.png"))); // NOI18N
        btnVacunas.setBorderPainted(false);
        btnVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacunasActionPerformed(evt);
            }
        });

        btnChequeos.setBackground(new java.awt.Color(255, 255, 255));
        btnChequeos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnChequeos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/chequeoMenuP.png"))); // NOI18N
        btnChequeos.setBorderPainted(false);
        btnChequeos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChequeosActionPerformed(evt);
            }
        });

        btnGrupos.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/gruposMenuP.png"))); // NOI18N
        btnGrupos.setBorderPainted(false);
        btnGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGruposActionPerformed(evt);
            }
        });

        btnProduccion.setBackground(new java.awt.Color(255, 255, 255));
        btnProduccion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/produccionMenuP.png"))); // NOI18N
        btnProduccion.setBorderPainted(false);
        btnProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduccionActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(255, 255, 255));
        btnReportes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/reporteMenuP.png"))); // NOI18N
        btnReportes.setBorderPainted(false);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/usuarioMenuP.png"))); // NOI18N
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnPropietarios.setBackground(new java.awt.Color(255, 255, 255));
        btnPropietarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/propietarioMenuP.png"))); // NOI18N
        btnPropietarios.setBorderPainted(false);
        btnPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropietariosActionPerformed(evt);
            }
        });

        lblAnimales.setText("Animales");

        lblProduccion.setText("Producciones");

        lblVacunas.setText("Vacunas");

        lblChequeos.setText("Chequeos");

        lblGrupos.setText("Grupos");

        lblReportes.setText("Reportes");

        lblUsuarios.setText("Usuarios");

        lblPropietarios.setText("Propietarios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblAnimales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(lblProduccion))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVacunas)
                                    .addComponent(btnChequeos)
                                    .addComponent(btnGrupos)
                                    .addComponent(lblChequeos)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblGrupos)
                                            .addComponent(lblVacunas))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPropietarios)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnReportes)
                                            .addComponent(btnUsuarios)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblReportes)
                                                    .addComponent(lblUsuarios))))
                                        .addComponent(btnPropietarios, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAnimales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProduccion)
                        .addGap(41, 41, 41))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProduccion)
                    .addComponent(lblAnimales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReportes)
                    .addComponent(btnVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVacunas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblReportes))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChequeos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarios)
                    .addComponent(lblChequeos))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrupos)
                    .addComponent(btnPropietarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGrupos)
                    .addComponent(lblPropietarios))
                .addGap(16, 16, 16))
        );

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/btnCancelar.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblTitulo2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblTitulo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/logo.png"))); // NOI18N
        lblTitulo2.setText("Redpoll");

        lblCerrar.setText("Cerrar Sesión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCerrar)
                        .addGap(15, 15, 15))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuHandler(int i){
        switch(i){
            case 1:
                JFAnimal menuAnimal = new JFAnimal();
                menuAnimal.setVisible(true);
                menuAnimal.setResizable(false);
                menuAnimal.setLocationRelativeTo(this);
                break;
            case 2:
                GuiProduccion menuProd = new GuiProduccion();
                menuProd.setVisible(true);
                menuProd.setResizable(false);
                menuProd.setLocationRelativeTo(this);
                break;
            case 3:
                JFVacuna menuVac = new JFVacuna();
                menuVac.setVisible(true);
                menuVac.setResizable(false);
                menuVac.setLocationRelativeTo(this);
                break;
            case 4:
                MenuReportes menuRep = new MenuReportes();
                menuRep.setVisible(true);
                menuRep.setResizable(false);
                menuRep.setLocationRelativeTo(null);
                break;
            case 5:
                JFChequeo menuChequeo = new JFChequeo();
                menuChequeo.setVisible(true);
                menuChequeo.setResizable(false);
                menuChequeo.setLocationRelativeTo(this);
                break;
            case 6:
                //GuiUsuarios menuUsr = new GuiUsuarios();
                //menuUsr.setVisible(true);
                //menuUsr.setResizable(false);
                //menuUsr.setLocationRelativeTo(this);
                //break;
            case 7:
                NuevoFormularioGrupo menuGrup = new NuevoFormularioGrupo();
                menuGrup.setVisible(true);
                menuGrup.setResizable(false);
                menuGrup.setLocationRelativeTo(this);
                break;
            case 8:
                GuiPropietario menuPropietarios = new GuiPropietario();
                menuPropietarios.setVisible(true);
                menuPropietarios.setResizable(false);
                menuPropietarios.setLocationRelativeTo(this);
                break;
            case 9:
                InterfazLogin menuLogin = new InterfazLogin();
                menuLogin.setVisible(true);
                menuLogin.setResizable(false);
                menuLogin.setLocationRelativeTo(this);
                break;
                
        }
        this.dispose();
    }
    
    private void btnPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropietariosActionPerformed
        this.menuHandler(8);
    }//GEN-LAST:event_btnPropietariosActionPerformed

    private void btnProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduccionActionPerformed
        this.menuHandler(2);
    }//GEN-LAST:event_btnProduccionActionPerformed

    private void btnAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalesActionPerformed
        this.menuHandler(1);
    }//GEN-LAST:event_btnAnimalesActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.menuHandler(9);
        
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacunasActionPerformed
        this.menuHandler(3);
    }//GEN-LAST:event_btnVacunasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        this.menuHandler(4);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnChequeosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChequeosActionPerformed
        this.menuHandler(5);
    }//GEN-LAST:event_btnChequeosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        this.menuHandler(6);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGruposActionPerformed
        this.menuHandler(7);
    }//GEN-LAST:event_btnGruposActionPerformed
    
    public static void menuReportes(){
        MenuReportes menuRep = new MenuReportes();
                menuRep.setVisible(true);
                menuRep.setResizable(false);
                menuRep.setLocationRelativeTo(null);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimales;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnChequeos;
    private javax.swing.JButton btnGrupos;
    private javax.swing.JButton btnProduccion;
    private javax.swing.JButton btnPropietarios;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVacunas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnimales;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblChequeos;
    private javax.swing.JLabel lblGrupos;
    private javax.swing.JLabel lblProduccion;
    private javax.swing.JLabel lblPropietarios;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lblVacunas;
    // End of variables declaration//GEN-END:variables
}
