/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package redpoll.ClasesProduccion;

import javax.swing.JOptionPane;

/**
 *
 * @author jefte
 */
public class GuiAgregarProduccion extends javax.swing.JDialog {

    /**
     * Creates new form GuiAgregarProduccion
     */
    public GuiAgregarProduccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        
        initComponents(); 
        this.setLocationRelativeTo(parent);
    }
    
    public double validarInt(String input){
       if(input.matches("[0-9]+")){
            return Double.parseDouble(input);
       } else{
            JOptionPane.showMessageDialog(null,"Error debe ingresar unicamente números");
            
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        lblOrdeñoMañana = new javax.swing.JLabel();
        txtOrdeñoMañana = new javax.swing.JTextField();
        lblOrdeñoTarde = new javax.swing.JLabel();
        txtOrdeñoTarde = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblOrdeñoMañana.setText("Ordeño de la mañana");

        txtOrdeñoMañana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdeñoMañanaActionPerformed(evt);
            }
        });

        lblOrdeñoTarde.setText("Ordeño de la tarde");

        txtOrdeñoTarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdeñoTardeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblOrdeñoTarde)
                    .addComponent(lblOrdeñoMañana)
                    .addComponent(txtOrdeñoMañana)
                    .addComponent(txtOrdeñoTarde, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addContainerGap(536, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblOrdeñoMañana)
                .addGap(18, 18, 18)
                .addComponent(txtOrdeñoMañana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblOrdeñoTarde)
                .addGap(18, 18, 18)
                .addComponent(txtOrdeñoTarde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrdeñoTardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdeñoTardeActionPerformed
     
    }//GEN-LAST:event_txtOrdeñoTardeActionPerformed

    private void txtOrdeñoMañanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdeñoMañanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdeñoMañanaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        double datoMañana = validarInt(this.txtOrdeñoMañana.getText());
        double datoTarde = validarInt(this.txtOrdeñoTarde.getText());
        JOptionPane.showMessageDialog(null,"Ordeño Mañana: "+ datoMañana + "\n Dato Tarde: " + datoTarde);
        this.dispose();

    }//GEN-LAST:event_btnAgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblOrdeñoMañana;
    private javax.swing.JLabel lblOrdeñoTarde;
    private javax.swing.JTextField txtOrdeñoMañana;
    private javax.swing.JTextField txtOrdeñoTarde;
    // End of variables declaration//GEN-END:variables
}
