/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package redpoll.ClasesProduccion;

import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jefte
 */

//Menú Principal para la gestión de las producciones
public class GuiProduccion extends javax.swing.JFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    private GestionProduccion gestionProduccion;

    /**
     * Creates new form GestionProduccion
     */
    public GuiProduccion() {
        this.setUndecorated(true);
        //Instanciamos la clase con el menú para Agregar Producciones
        this.gestionProduccion = new GestionProduccion();
        initComponents();
        String[] nombreColumnas = new String[]{"Id", "Ordeño Mañana", "Ordeño Tarde", "Total", "Fecha"};
        this.modelo.setColumnIdentifiers(nombreColumnas);
        this.tbProducciones.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarProduccion = new javax.swing.JButton();
        btnEditarProduccion = new javax.swing.JButton();
        btnEliminarProduccion = new javax.swing.JButton();
        btnMostrarProduccion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProducciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestion Producciones");

        btnAgregarProduccion.setText("Agregar Produccion");
        btnAgregarProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProduccionActionPerformed(evt);
            }
        });

        btnEditarProduccion.setText("Editar Produccion");

        btnEliminarProduccion.setText("Eliminar Produccion");

        btnMostrarProduccion.setText("Mostrar Produccion");
        btnMostrarProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarProduccionActionPerformed(evt);
            }
        });

        tbProducciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbProducciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnAgregarProduccion)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEditarProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnEliminarProduccion)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProduccionActionPerformed
        this.abrirFormularioProduccion(null);
    }//GEN-LAST:event_btnAgregarProduccionActionPerformed

    private void btnMostrarProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarProduccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarProduccionActionPerformed
    
    //Método para abrir un modal en el que ingresar una nueva produccion
    private void abrirFormularioProduccion(Produccion produccion){
        GuiAgregarProduccion gui = new GuiAgregarProduccion(this,true,produccion);
        gui.setVisible(true);
        if(gui.confirmacion()){
            Produccion prod = gui.consultarProduccion();
            if(produccion ==null){
              
                this.gestionProduccion.agregarProduccion(prod);
            }else{
                
                this.gestionProduccion.editarProduccion(prod);
            }
            this.cargarTabla();
        }
    }
    
   private void cargarTabla() {
        this.modelo.setRowCount(0);
        //System.out.println(gestionProduccion.getProducciones().values());
        for (Produccion produccion : gestionProduccion.getProducciones().values()) {
            System.out.println(produccion.getOrdeñoMañana()+" "+ produccion.getOrdeñoTarde() +" "+ produccion.getTotal() +" "+ produccion.getFecha());
            this.modelo.addRow(new Object[]{produccion.getOrdeñoMañana(), produccion.getOrdeñoTarde(), produccion.getTotal(), produccion.getFecha()});
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProduccion;
    private javax.swing.JButton btnEditarProduccion;
    private javax.swing.JButton btnEliminarProduccion;
    private javax.swing.JButton btnMostrarProduccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProducciones;
    // End of variables declaration//GEN-END:variables
}
