/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package redpoll.chequeos;

import redpoll.animales.*;
import redpoll.produccion.*;
import javax.swing.JCheckBox;

/**
 *
 * @author jefte
 */
public class FiltroChequeo extends javax.swing.JDialog {
    private String[] datos = {"", "", ""};
    private boolean confirmar;
    /**
     * Creates new form NewJDialog
     */
    public FiltroChequeo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(parent);
        this.confirmar=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        checkFecha = new javax.swing.JCheckBox();
        txtFecha = new javax.swing.JTextField();
        txtNombreVeterinario = new javax.swing.JTextField();
        checkNombreVeterinario = new javax.swing.JCheckBox();
        btnAceptar = new javax.swing.JButton();
        checkAnimal = new javax.swing.JCheckBox();
        txtAnimal = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        checkVacuna = new javax.swing.JCheckBox();
        txtVacuna = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPanel.setBackground(new java.awt.Color(235, 207, 178));

        checkFecha.setBackground(new java.awt.Color(235, 207, 178));
        checkFecha.setText("Fecha");
        checkFecha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkFechaStateChanged(evt);
            }
        });
        checkFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFechaActionPerformed(evt);
            }
        });

        txtFecha.setEnabled(false);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        txtNombreVeterinario.setEnabled(false);
        txtNombreVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreVeterinarioActionPerformed(evt);
            }
        });

        checkNombreVeterinario.setBackground(new java.awt.Color(235, 207, 178));
        checkNombreVeterinario.setText("Nombre Veterinario");
        checkNombreVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNombreVeterinarioActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/btnRegistrarse.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        checkAnimal.setBackground(new java.awt.Color(235, 207, 178));
        checkAnimal.setText("Animal");
        checkAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnimalActionPerformed(evt);
            }
        });

        txtAnimal.setEnabled(false);
        txtAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnimalActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redpoll/Imgs/filtrado.png"))); // NOI18N
        lblTitulo.setText("Filtrado");

        checkVacuna.setBackground(new java.awt.Color(235, 207, 178));
        checkVacuna.setText("Vacuna");
        checkVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVacunaActionPerformed(evt);
            }
        });

        txtVacuna.setEnabled(false);
        txtVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVacunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblTitulo))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnAceptar))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkNombreVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(27, 27, 27)
                .addComponent(checkFecha)
                .addGap(18, 18, 18)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkNombreVeterinario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(checkAnimal)
                .addGap(18, 18, 18)
                .addComponent(txtAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(checkVacuna)
                .addGap(18, 18, 18)
                .addComponent(txtVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnAceptar)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public boolean confirmacion() {
       return this.confirmar;
    }    
    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        
    }//GEN-LAST:event_txtFechaActionPerformed
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        //arreglo donde se van a guardar datos del filtro
        datos[0] = (this.txtFecha.isEnabled()) ? this.txtFecha.getText() : "";
        datos[1] = (this.txtNombreVeterinario.isEnabled()) ? this.txtNombreVeterinario.getText() : "";
        datos[2] = (this.txtAnimal.isEnabled()) ? this.txtAnimal.getText() : "";
        
        this.confirmar = true;
        this.setVisible(false);
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    public String getDatos(int indice) {

        //se obtienen los datos
        return datos[indice];
    }
    
    private void txtNombreVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreVeterinarioActionPerformed

    //Estos metodos se encargan de habilitar los campos de texto 
    private void checkNombreVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNombreVeterinarioActionPerformed
        this.txtNombreVeterinario.setEnabled((this.txtNombreVeterinario.isEnabled()) ? false : true);
    }//GEN-LAST:event_checkNombreVeterinarioActionPerformed

    private void checkFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFechaActionPerformed
        this.txtFecha.setEnabled((this.txtFecha.isEnabled()) ? false : true);
    }//GEN-LAST:event_checkFechaActionPerformed

    private void checkAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnimalActionPerformed
        this.txtAnimal.setEnabled((this.txtAnimal.isEnabled()) ? false : true);
    }//GEN-LAST:event_checkAnimalActionPerformed

    
    public boolean getCheckAnimal() {
        return checkAnimal.isSelected();
    }

    public boolean getCheckFecha() {
        return checkFecha.isSelected();
    }

    public boolean getCheckNombreVeterinario() {
        return checkNombreVeterinario.isSelected();
    }


    private void txtAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnimalActionPerformed

    private void checkFechaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkFechaStateChanged
    }//GEN-LAST:event_checkFechaStateChanged

    private void checkVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVacunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkVacunaActionPerformed

    private void txtVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVacunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVacunaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JCheckBox checkAnimal;
    private javax.swing.JCheckBox checkFecha;
    private javax.swing.JCheckBox checkNombreVeterinario;
    private javax.swing.JCheckBox checkVacuna;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAnimal;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombreVeterinario;
    private javax.swing.JTextField txtVacuna;
    // End of variables declaration//GEN-END:variables
}
